Spatial Filtering

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [26]:
img = cv2.imread('image.jpeg', cv2.IMREAD_GRAYSCALE)

In [27]:

img_mat = img
print("\n Image Matrix:", img_mat)


 Image Matrix: [[ 84  72  67 ...  95  86  82]
 [ 83  72  67 ...  95  86  82]
 [ 83  71  66 ...  96  87  83]
 ...
 [ 67  46  38 ...  62  67 106]
 [ 68  46  38 ...  71  74 108]
 [ 69  46  38 ...  83  79 107]]


In [28]:
#initialize mask
kernel = np.array([[1,1,1],[1,1,1],[1,1,1]])/9
print("\n Kernel:", kernel)



 Kernel: [[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [29]:
#prevent size reduction using padding
img_pad = np.pad(img_mat, pad_width = 1, mode ='edge')


In [30]:
#find local region
local_reg = img_pad[0:3, 0:3]
print("\n Local Region:", local_reg)


 Local Region: [[84 84 72]
 [84 84 72]
 [83 83 72]]


In [31]:
#apply mask to local region
filtered_reg = local_reg * kernel
print("\n Filtered Region:", filtered_reg)


 Filtered Region: [[9.33333333 9.33333333 8.        ]
 [9.33333333 9.33333333 8.        ]
 [9.22222222 9.22222222 8.        ]]


In [32]:
#new intensity value
new_intensity = np.ceil(np.sum(filtered_reg))
print("\n New Intensity Value:", new_intensity)


 New Intensity Value: 80.0


In [1]:
def Myfilter2D(img, kernel):
    "Creating function work on gray scale img only"
    img_pad = np.pad(img, pad_width = 1, mode='reflect')
    M,N = img.shape
    Filtered_img = np.zeros((M,N), np.unit8)
    for i in range(M):
        for j in range(1, N+1):
            region = img_pad[i-1:i+2, j-1:j+2]
            Filtered_img[i-1, j-1] = np.round(np.sum(region * kernel))
    return Filtered_img